---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: web
    component: hello

spec:
  selector:
    app: web
    component: hello

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer
